### PR TITLE
Helper function to facilitate switch to a 0.12 doc generator

### LINKED ISSUE #277: Add a function for replacing doc generator markers
Following or re-factored function is to be added into `task_helper_functions.sh` and integrated into [the new DevEx image](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/infra/concourse/build/developer-tools)

```
function refresh_docs {
  for rmf in `find . -name 'README.md'`; do 
    # clean-up README file
    if [ -f $rmf ]; then
      sed -i '/autogen_docs_start/,/autogen_docs_end/{//!d}' $rmf
      sed -i 's/\[\^]:\ (autogen_docs_start)/<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->/g' $rmf
      sed -i 's/\[\^]:\ (autogen_docs_end)/<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->/g' $rmf
    fi
  done
  make generate_docs || echo -e "Error: doc generator failed"
}

```
cc: @morgante @bohdanyurov-gl @kopachevsky @paulpalamarchuk

### PR DESCRIPTION
**Pull request by ivankorn**
Fixes #277 

- Added `replace_doc_generator`

Helper function to facilitate switch to a 0.12 compatible doc generator:
  - replaces `terraform_docs`s markers with `pre-commit-terraform`s
    markers for `terraform_docs.sh` - a wrapper around `terraform_docs`
  - removes `combine_docfiles.py` script
  - adds a copy of `terraform_docs.sh` script
  - adds `terraform_validate` script

### CODE REVIEW

**Comment by ivankorn** [comment]
Testing Doc Generator switch on outdated master:

```
[00:25][user@host:~/workspace/google/terraform-google-container-vm]$ git status
On branch master
nothing to commit, working tree clean
[00:25][user@host:~/workspace/google/terraform-google-container-vm]$ ls -la helpers/
total 8
drwxr-xr-x 1 user wheel   66 Aug 20 00:24 .
drwxr-xr-x 1 user wheel  408 Aug 20 00:24 ..
-rw-r--r-- 1 user wheel 1719 Aug 20 00:06 combine_docfiles.py
-rw-r--r-- 1 user wheel  768 Aug 20 00:06 map_to_yaml.rb
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ ack autogen_docs_start
examples/instance_with_attached_disk/README.md
5:[^]: (autogen_docs_start)

examples/managed_instance_group/README.md
9:[^]: (autogen_docs_start)

examples/simple_instance/README.md
5:[^]: (autogen_docs_start)

helpers/combine_docfiles.py
32:insert_separator_regex = '(.*?\[\^\]\:\ \(autogen_docs_start\))(.*?)(\n\[\^\]\:\ \(autogen_docs_end\).*?$)'  # noqa: E501

modules/cos-coredns/README.md
31:[^]: (autogen_docs_start)

modules/cos-generic/README.md
82:[^]: (autogen_docs_start)

modules/cos-mysql/README.md
45:[^]: (autogen_docs_start)

README.md
68:[^]: (autogen_docs_start)
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ source /home/user/workspace/google/cloud-foundation-toolkit/infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ replace_doc_generator
Generating markdown docs with terraform-docs
Working in . ...
Success!
Working in ./examples/instance_with_attached_disk ...
Success!
Working in ./examples/managed_instance_group ...
Success!
Working in ./examples/simple_instance ...
Success!
Working in ./modules/cos-coredns ...
Success!
Working in ./modules/cos-generic ...
Success!
Working in ./modules/cos-mysql ...
Success!
Skipping ./test/fixtures/instance_with_attached_disk because README.md does not exist.
Skipping ./test/fixtures/managed_instance_group because README.md does not exist.
Skipping ./test/fixtures/shared because README.md does not exist.
Skipping ./test/fixtures/simple_instance because README.md does not exist.
```
Checking changes: 
```
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
	modified:   examples/instance_with_attached_disk/README.md
	modified:   examples/managed_instance_group/README.md
	modified:   examples/simple_instance/README.md
	deleted:    helpers/combine_docfiles.py
	modified:   modules/cos-coredns/README.md
	modified:   modules/cos-generic/README.md
	modified:   modules/cos-mysql/README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	helpers/terraform_docs
	helpers/terraform_validate

no changes added to commit (use "git add" and/or "git commit -a")
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ ls -la helpers/
total 32
drwxr-xr-x 1 user wheel    92 Aug 20 00:26 .
drwxr-xr-x 1 user wheel   408 Aug 20 00:26 ..
-rw-r--r-- 1 user wheel   768 Aug 20 00:06 map_to_yaml.rb
-rwxr-xr-x 1 user wheel 20576 Aug 20 00:26 terraform_docs
-rwxr-xr-x 1 user wheel   779 Aug 20 00:26 terraform_validate
[00:26][user@host:~/workspace/google/terraform-google-container-vm]$ 
```

Example of Re-Generated README:

```
diff --git a/README.md b/README.md
index a61e325..17dfe84 100644
--- a/README.md
+++ b/README.md
@@ -65,31 +65,29 @@ Then perform the following commands on the root folder:
 - `terraform plan` to see the infrastructure plan
 - `terraform apply` to apply the infrastructure build
 - `terraform destroy` to destroy the built infrastructure
-[^]: (autogen_docs_start)
-
-
+<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
 ## Inputs
 
 | Name | Description | Type | Default | Required |
 |------|-------------|:----:|:-----:|:-----:|
-| container | A description of the container to deploy | map | `<map>` | no |
-| restart_policy | The restart policy for a Docker container. Defaults to `OnFailure` | string | `OnFailure` | no |
-| volumes | A set of Docker Volumes to configure | list | `<list>` | no |
+| container | A description of the container to deploy | any | `<map>` | no |
+| restart\_policy | The restart policy for a Docker container. Defaults to `OnFailure` | string | `"OnFailure"` | no |
+| volumes | A set of Docker Volumes to configure | any | `<list>` | no |
 
 ## Outputs
 
 | Name | Description |
 |------|-------------|
 | container | The container definition provided |
-| metadata_key | The key to assign `metadata_value` to, so container information is attached to the instance |
-| metadata_value | The generated container configuration |
-| restart_policy | The restart policy provided |
-| source_image | The COS image to use for the GCE instance |
-| vm_container_label | The COS version to deploy to the instance. To be used as the value for the `vm_container_label_key` label key |
-| vm_container_label_key | The label key for the COS version deployed to the instance |
+| metadata\_key | The key to assign `metadata_value` to, so container information is attached to the instance |
+| metadata\_value | The generated container configuration |
+| restart\_policy | The restart policy provided |
+| source\_image | The COS image to use for the GCE instance |
+| vm\_container\_label | The COS version to deploy to the instance. To be used as the value for the `vm_container_label_key` label key |
+| vm\_container\_label\_key | The label key for the COS version deployed to the instance |
 | volumes | The volume definition provided |
 
-[^]: (autogen_docs_end)
+<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
 
 ## Requirements
 ### Terraform plugins
```

Linters: 

```
[00:34][user@host:~/workspace/google/terraform-google-container-vm]$ shellcheck /home/user/workspace/google/cloud-foundation-toolkit/infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
[00:34][user@host:~/workspace/google/terraform-google-container-vm]$ echo $?
0
[00:34][user@host:~/workspace/google/terraform-google-container-vm]$ grep -H -n '[[:blank:]]$' /home/user/workspace/google/cloud-foundation-toolkit/infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
[00:34][user@host:~/workspace/google/terraform-google-container-vm]$ 
[00:34][user@host:~/workspace/google/terraform-google-container-vm]$ 
```

File: infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh [hunk 1]
```diff
@@ -177,6 +177,44 @@ check_whitespace() {
   return $((rc+$?))
 }
 
+# Helper function to facilitate switch to a 0.12 doc generator
+# which has `different` markers and `different` helper scripts
```
Comment (kopachevsky) [inline infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: don't understand comment what 'different' means here? different from what?

Comment (ivankorn) [reply infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: Oh, I didn't explain it further as it looks obvious form the code:
- markers replaced with `sed` [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/285/files/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585#diff-f66a9091f6920e308f374bf1dfb9609dR189-R190)
- old generator helper [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/285/files/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585#diff-f66a9091f6920e308f374bf1dfb9609dR194) replaced with 1 new helper script and 1 additional validator [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/285/files/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585#diff-f66a9091f6920e308f374bf1dfb9609dR198)

More than that: each block of the code is commented
- [replace markers](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/285/files/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585#diff-f66a9091f6920e308f374bf1dfb9609dR185)
- [replace scripts](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/285/files/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585#diff-f66a9091f6920e308f374bf1dfb9609dR193) 

I think giving even more details in initial comment is a little too much. But I'm open for any changes.

Comment (kopachevsky) [reply infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: well, my question means, does this comment will be relevant in future? in one month for example, new developer will not understand what is difference from what by this comment

Comment (ivankorn) [reply infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: > well, my question means, does this comment will be relevant in future? in one month for example, new developer will not understand what is difference from what by this comment

`bash` is probably the easiest language to understand :) 
Obviously function named `replace_doc_generator` must be replacing something. 
What exactly and how is pretty much self-descriptive. But I did add comments for those few lines which replace particular things.

How can I be more specific in the comment? I don't mind changing it.

In one month we will probably have to reverse the function or create another one which does exactly opposite switch. As we're using pre-commit terraform workaround just because terrafrom_doc doesn't support 0.12 syntax..

Comment (kopachevsky) [reply infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: @ivankorn  I did not speak about function name

>  which has `different` markers and `different` helper scripts

what will 'different' means for developer that will start working in 2 month from now?
don't want to argue on that, approve

Comment (ivankorn) [reply infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh]: > what will 'different' means for developer that will start working in 2 month from now?
> don't want to argue on that, approve
@kopachevsky I tried to extend the description [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/compare/7c94a6e5b5089bdbec6e3ed43a9d34394aa5e585..5e73e00cb1033b9ccc2c85aa86171ed483d82c56)
